name: Build EveVPN APK
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build APK with Docker
        run: |
          docker run --rm -v "$(pwd)":/home/buildozer/hostport buildozer/buildozer --version
          docker run --rm -v "$(pwd)":/home/buildozer/hostport buildozer/buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: EveVPN-Package
          path: bin/*.apk
